name: Release

on:
  workflow_dispatch:

jobs:
  create_package:
    uses: ./.github/workflows/create-package.yml

  release:
    runs-on: ubuntu-latest
    needs: create_package
    permissions:
      contents: write
    env:
      artifactsPath: ${{ github.workspace }}/artifacts
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Artifacts
        id: download-artifacts
        uses: actions/download-artifact@v4
        with:
          path: ${{ env.artifactsPath }}

      # Make a release tag of the version from the package.json file
      - name: Create Tag
        id: tag_version
        uses: rickstaa/action-create-tag@a1c7777fcb2fee4f19b0f283ba888afa11678b72
        with:
          tag: ${{ needs.create_package.outputs.version }}

      # Publish the Release to GitHub
      - name: Make Release
        uses: softprops/action-gh-release@c062e08bd532815e2082a85e87e3ef29c3e6d191
        with:
          generate_release_notes: true
          files: |
            ${{ env.artifactsPath }}/**/*
          tag_name: ${{ needs.create_package.outputs.version }}
